### ISSUE TITLE
Problem with showing lines

### ISSUE THREAD

**Issue by Dvjack** [Nushaine/lane-detection#1]
Nushaine, 
     I've come across a problem when trying to implement the part where you are displaying the lines from the hough transform. I am getting an error where it says there isn't enough values to unpack (see screenshot). I did print the output of 'lines' and it seems to be outputting 4 values. Please let me know if you know why I am getting this error.
@Nushaine 
![houghlineserror](https://user-images.githubusercontent.com/79436134/112895986-d60e4980-90ab-11eb-891c-00eedb445232.JPG)

**Comment by Nushaine** [comment]
The problem is your 'lines' variable is a double nested array. Instead of being: [[x,y], [x, y]], your array is [[[x, y]], [[x, y]]]. If you'd loop through that list, all you'd get is the list [x, y], not each individual element. Maybe you add an extra set of brackets somewhere?

**Comment by Dvjack** [comment]
Great point! I'm sure that is the issue, although I don't see where I've added any extra brackets in the 'lines' variable. Is there anywhere else additional brackets could have been added outside of this variable?

**Comment by Dvjack** [comment]
Great point! I'm sure that is the issue, although I don't see where I've added any extra brackets in the 'lines' variable. Is there anywhere else additional brackets could have been added outside of this variable?
